services:
  lightmirrors:
    image: lightmirrors/mirrors
    build:
      context: ./src
    volumes:
      - ./src/:/app
      - ./data/cache:/app/cache
    env_file:
      - .env
    environment:
      - SSL_SELF_SIGNED=false
    networks:
      - app
    restart: unless-stopped
    # for linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
  caddy:
    image: lightmirrors/caddy
    build:
      context: caddy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data/caddy
    env_file:
      - .env
    networks:
      - app
    restart: unless-stopped
  aria2:
    image: lightmirrors/aria2
    build: ./aria2
    volumes:
      - ./aria2/aria2.conf:/aria2.conf
      - ./data/cache:/app/cache
      - ./data/aria2:/data/
    networks:
      - app
    env_file:
      - .env
    restart: unless-stopped
networks:
  app:
    name: lightmirrors_app
    driver: bridge