---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightmirrors-aria2
  namespace: lightmirrors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lightmirrors-aria2
  template:
    metadata:
      labels:
        app: lightmirrors-aria2
    spec:
      containers:
        - name: aria2
          image: lightmirrors/aria2:v0.0.1 # Not on DockerHub. You need to build and post image yourself
          ports:
            - name: http
              containerPort: 6800
          env:
            - name: no_proxy
              value: "lightmirrors-mirror.lightmirrors"
            - name: RPC_SECRET
              value: changeMe
          volumeMounts:
            - name: cache-volume
              mountPath: /app/cache
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: lightmirrors-pvc
