---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lightmirrors-pvc
  namespace: lightmirrors
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 90Gi
  storageClassName: nfs-sc
