name: Manual CI

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: noclin
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./src
          tags: ghcr.io/noclin/lightmirrors:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./aria2
          tags: ghcr.io/noclin/lightmirrors_aria2:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Integration Test
        run: python3 test/runner.py